### ISSUE TITLE
creation influenced_by triples are all Agent

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#112]
agentInfluenced triple needs to check Class before assigning/only assign to People/Groups.

See Peter's comment in https://github.com/project-lux/lux-marklogic/issues/233.

**Comment by clarkepeterf** [comment]
@kkdavis14 I believe there may also need to be checks that the subject is a Work

**Comment by kkdavis14** [comment]
@clarkepeterf refactor will only add `influenced_by_{type}` to Works or Concepts, will check type of influencing record before assigning in triple. 
`agentInfluencedCreation` will go away. if approved anyway!

**Comment by kkdavis14** [comment]
@clarkepeterf the final update:
we were previously creating two different triples for creation influenced by-

one was `agentInfluencedCreation` that was erroneously being assigned to things that were not Agents.
the other was `influenced_by_{type}` which was only going on Concepts.

now there is one, which checks for the type of record doing the influencing to form:
`{luxns}{typeOfRecordDoingInfluencing}Influenced{activityBeingInfluenced}`
e.g.
`"https://lux.collections.yale.edu/ns/agentInfluencedCreation"`
or 
`"https://lux.collections.yale.edu/ns/conceptInfluencedCreation"`
or 
`"https://lux.collections.yale.edu/ns/activityInfluencedProduction"`

This works for both Creation and Production, so we can't limit it to subject == Works as suggested.
