### ISSUE TITLE
The Trouble with Triples II

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#151]
I have some questions about triple creation.

1. should HMOs be "items"? see type_map but then in the code they're often just "object"
2. why are some triples created twice (or 4 times?) e.g. lines 512-525 create the same triple with LUX and CIDOC predicates. then create the same again with more class-specific LUX predicates. what is the use for this?

**Comment by azaroth42** [comment]
1. Yes -- this is a bug (e.g. should be `about_or_depicts_item`, not `about_or_depicts_object`)
2. the multiple triples are used for different searches. e.g. if x is a LinguisticObject and y is a Person, then all of these are useful: x about y (index of all 'abouts' regardless of type) / x about_or_depicts y (index of both about and depicts regardless of type) / x about_person y (about a person) / x about_or_depicts_person y (about or depicts a person)

**Comment by kkdavis14** [comment]
closed by #163
