### ISSUE TITLE
Sort title is missing in some records

### ISSUE THREAD

**Issue by brent-hartwig** [project-lux/data-pipeline#159]
Some records do not to have a title to sort by.  The backend is expecting them to be identified by `/json/identified_by[./classified_as/equivalent/id='http://vocab.getty.edu/aat/300451544']`.  Examples:

- With: https://lux.collections.yale.edu/data/person/8d1e529c-6853-4fef-8519-56e18f9ba3b0
- Without: https://lux.collections.yale.edu/data/person/81ed8efd-5dbd-4ddc-9d2c-c3609483da92

Impact: when sorted by name, they are always last regardless of sort direction.
 
Related ticket: [ML 363](https://github.com/project-lux/lux-marklogic/issues/363)

**Comment by azaroth42** [comment]
We think we've fixed it, hopefully in next build

**Comment by brent-hartwig** [comment]
^-- dataset 2024-11-23

**Comment by brent-hartwig** [comment]
Indeed, the last results for agents born/started at London are different between ascending and descending order.  Thanks!

* [Last page, ascending](https://lux-front-sbx.collections.yale.edu/view/results/people?q=%7B%22startAt%22%3A%7B%22name%22%3A%22London%22%7D%7D&as=anySortName%3Aasc&ap=344)
* [Last page, descending](https://lux-front-sbx.collections.yale.edu/view/results/people?q=%7B%22startAt%22%3A%7B%22name%22%3A%22London%22%7D%7D&as=anySortName%3Adesc&ap=344)

**Comment by kkdavis14** [comment]
@brent-hartwig excellent, good to confirm it's widespread fixed!
