### ISSUE TITLE
Split OCLC Source into VIAF and FAST

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#175]
Currently, both sources are under OCLC. We should split the files into VIAF and FAST Classes & functions and treat them separately, to match the file structure of other external sources.

**Comment by wjbmattingly** [comment]
Would it be okay if we merged this issue with #174 ? It feels like a task inside of that issue.

**Comment by kkdavis14** [comment]
@wjbmattingly sure!

**Comment by kkdavis14** [comment]
closing in favor of #174
