### ISSUE TITLE
Add triples for new searches: agent that influenced the production of an object, work about an object or work

### ISSUE THREAD

**Issue by azaroth42** [project-lux/data-pipeline#19]
In the ML mapper, add these

lux:agentInfluencedProduction
lux:workAboutWork
lux:workAboutObject

**Comment by kkdavis14** [comment]
blockshttps://github.com/project-lux/lux-marklogic/issues/65

**Comment by kkdavis14** [comment]
lux:about_or_depicts_work
lux:about_or_depicts_object

**Comment by kkdavis14** [comment]
lux:agentInfluencedCreation
lux:agentInfluencedProduction

**Comment by azaroth42** [comment]
Done.
