### ISSUE TITLE
Ensure that sorting uses `sort title` not `inverted terms`

### ISSUE THREAD

**Issue by azaroth42** [project-lux/data-pipeline#21]
Currently for names that should be used for sorting we use:
> https://vocab.getty.edu/aat/300404672

But there's a better term:
> https://vocab.getty.edu/aat/300451544

which the Linked Art community also agreed should be used:
> https://github.com/linked-art/linked.art/issues/572#issuecomment-1981319306

And the suggestion there is also to ask for `sort value` from AAT for sorting by identifiers or other specific values that aren't themselves names.

**Comment by kkdavis14** [comment]
happy to email Antonio re: possible AAT term addition.

**Comment by kkdavis14** [comment]
besides a comment in final mapper, this is only referenced from/needs updated in the global config json.

**Comment by kkdavis14** [comment]
@azaroth42 Antonio to add `300456575` as `sort values` with LUX as the source, woo woo. 

As usual, not live for a few weeks til they publish new data.
