### ISSUE TITLE
Trash YUL catalog links on HMOs

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#23]
example rec:
https://lux.collections.yale.edu/view/object/f205a441-5895-4328-8ad8-655f56f2a7ce

one of those 150 or so links is the actual HMO, but we can't programmatically tell which. unit-data ticket to follow to ask YUL to not link Work bib records to LUX HMO records.

in the meantime, YUL mapper fix to trash subject_of if it's access_point starts "https://search.library.yale.edu/catalog/"

(ticket still being formed, see Teams convo)

**Comment by azaroth42** [comment]
Problem to be solved by YUL.
