### ISSUE TITLE
Add SNAC as a source

### ISSUE THREAD

**Issue by azaroth42** [project-lux/data-pipeline#3]
We can get the links from wikidata (amongst other places) and there's interesting information in the records... but the permalink and the data export URI don't match up.

https://www.wikidata.org/wiki/Q727693 which has SNAC ARK ID https://snaccooperative.org/ark:/99166/w67d3fsz

But the JSON export is https://snaccooperative.org/download/8895729?type=constellation_json

So we need a way to resolve w67d3fsz into 8895729.

Thankfully there's an API ...https://snaccooperative.org/api_help

But it only supports PUT of JSON parameters, making the retrieval a little more complex.

SNAC openrefine endpoint mentioned here: https://portal.snaccooperative.org/node/489

**Comment by azaroth42** [comment]
ahha!

https://snaccooperative.org/download?arkid=http://n2t.net/ark:/99166/w6jh3pk0&type=constellation_json :)

**Comment by kkdavis14** [comment]
My config looks like this:
{
    "name": "snac",
    "type": "external",
    "namespace": "https://snaccooperative.org",
    "matches": ["http://n2t.net/ark:/99166/"],
    "fetch": "https://snaccooperative.org/download?arkid=http://n2t.net/ark:/99166/{identifier}&type=constellation_json",
    "merge_order": 95,
    
    "fetcherClass": "sources.archives.snac.fetcher.SNACFetcher",
    "mapperClass": "sources.archives.snac.mapper.SNACMapper"
}
