### ISSUE TITLE
Why are these recs dying in pipeline?

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#36]
attribution assignments on the ids on this work:
https://lux-front-sbx.collections.yale.edu/data/text/55d93cc2-7a93-42d7-aed1-16a0b9452431

are not in YUL recordcache2, but made it past re-ider in testing.

**Comment by azaroth42** [comment]
They don't reidentify properly in the referring records for some reason. By the end of the process, they're fixed, so running reidentify on the recordcache records now works just fine. OCLC doesn't have a name (made a Yale issue for it) but the YUL record does.

**Comment by kkdavis14** [comment]
another example: `creation > influenced_by`
https://lux-front-tst.collections.yale.edu/data/concept/232e1dd6-0d83-4ab6-a723-df79e1a91065
