### ISSUE TITLE
Sync Getty vocabularies via activity stream

### ISSUE THREAD

**Issue by azaroth42** [project-lux/data-pipeline#41]
Getty's vocab stream is here:
  https://data.getty.edu/vocab/activity-stream 

But needs a slight tweak to get the URIs to be the "official" vocab ones, rather than data.getty.edu/

Museum stream is here:
  https://data.getty.edu/museum/collection/activity-stream 

GRI stream is here:
  https://data.getty.edu/research/collections/activity-stream

Which could then provide data for reconciliation (eg through ULAN)

**Comment by kkdavis14** [comment]
done?

**Comment by azaroth42** [comment]
Done now :)
