### ISSUE TITLE
How did Visual Work link from Dana HMO get dropped?

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#45]
https://lux-front-sbx.collections.yale.edu/view/object/1851ac0f-086b-424c-80a0-2d84a49f2138

very weird.

VI link returns a 404, but the YUAG rec exists in the data: https://media.art.yale.edu/content/lux/vis/54339.json

a *different* Dana VI exists:
https://lux-front-sbx.collections.yale.edu/view/visual/954c6a2d-71a3-4dd9-b9d9-77aaae04abd9

with no HMO. 

there should be two HMOs. is this something weird in the YUAG data or did pipeline sever for some reason?

Bugherd: https://www.bugherd.com/projects/284041/tasks/2135

**Comment by azaroth42** [comment]
--> internal Yale issue
