### ISSUE TITLE
Should pipeline only allow one birth/death location?

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#46]
https://lux-front-sbx.collections.yale.edu/data/person/7424fee6-4318-45e8-9dd0-d4bb71b073f4 has two for both activities

one of the Death locations is a 404 (and they're both supposedly DC, another issue).

but both Births are valid--one is a town, one a reservation. Front end will only ever display one (the first one). Currently rendering `unable to retrieve info` on the broken DC rec.

**Comment by azaroth42** [comment]
I was born in Rangiora, and I was born in New Zealand. The pipeline has no way to know which is more specific, or if they're not in a hierarchy, which one is correct. Similarly, the artwork is a panel painting and a painting.
