### ISSUE TITLE
Why is this rec returning a 404?

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#47]
https://lux-front-sbx.collections.yale.edu/data/person/7424fee6-4318-45e8-9dd0-d4bb71b073f4

two death locations, both of which are DC, but one is a 404. Why 404?

https://lux-front-sbx.collections.yale.edu/data/place/9ba89c26-82f9-4be6-a699-f26be9c0e193

**Comment by azaroth42** [comment]
--> Yale internal board please
