### ISSUE TITLE
Add member_of to item:any triple

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#84]
would fully solve https://www.bugherd.com/projects/284041/tasks/2279

but has performance implications. terrible idea right off the bat or something we should test? was asked by Peter.

**Comment by kkdavis14** [comment]
approved by Rob, needs implemented.

**Comment by azaroth42** [comment]
Actually not a data problem but an index configuration problem. The records ahve the triples, they're just not searched as Sets are excluded from the referencePrimaryName index as 99% of them are archives
eg
![Screenshot 2024-07-18 at 11 01 45 AM](https://github.com/user-attachments/assets/9675ad8a-4931-429e-aa6c-ef6cebc4fd4f)
