### ISSUE TITLE
Add triple for new search term/HAL link: works part_of works

### ISSUE THREAD

**Issue by kkdavis14** [project-lux/data-pipeline#85]
this work is a part_of another work:
https://lux-data-dev.collections.yale.edu/view/text/77a59f7f-227f-4e8d-8539-39fc39a15b3e

but the work it's a part of:
https://lux-data-dev.collections.yale.edu/view/text/66b917f7-6908-43aa-8e0e-5d2f4b26424c
doesn't have the link back.

As per Peter, needs a triple.

**Comment by azaroth42** [comment]
Defer until we can determine if this is an outlier that should be fixed somehow else, or is actually valuable.

**Comment by kkdavis14** [comment]
unit-data for them to investigate https://git.yale.edu/LUX/unit-data/issues/150

for me: look through all Works to see what they are a part_of and how many they are a part_of
